### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by noobugs** [VanLoo-lab/gritic#3]
Hi, Thank you for the amazing tool!  I am testing it on samples with ploidy around 4, however, the following err showed:

./envs/gritic-0.0.3/lib/python3.12/site-packages/gritic/gritictimer.py:651: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  timing_table_prev = pd.read_csv(timing_table_path,sep='\t')
Traceback (most recent call last):
  File "~/rungritic_cmd.py", line 67, in <module>
    gritictimer.process_sample(sample,output_dir,plot_trees=plot_trees,wgd_override=sample_wgd_status,non_parsimony_penalty=non_parsimony_penalty)
  File "~/envs/gritic-0.0.3/lib/python3.12/site-packages/gritic/gritictimer.py", line 1050, in process_sample
    sample_posterior_table = posteriortablegen.get_sample_posterior_table(timing_table_path,output_dir,sample.sample_id,apply_penalty=apply_penalty)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/py39_4.12.0/envs/gritic-0.0.3/lib/python3.12/site-packages/gritic/posteriortablegen.py", line 94, in get_sample_posterior_table
    segment_frame = produce_timing_segment_table(segment_table,timing_dict,segment_id,n_samples=100)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/envs/gritic-0.0.3/lib/python3.12/site-packages/gritic/posteriortablegen.py", line 52, in produce_timing_segment_table
    route = np.random.choice(segment_table.Route,p=probs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 971, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN.

Could you pls so kind help with it?

Thank you so much!

**Comment by tlesluyes** [comment]
Hi @noobugs,

I experienced a very similar issue on my dataset because my `mutation_table` contained both clonal and subclonal SNVs (although the doc specifically mentions that I shouldn't be doing that). It ran fine when I removed non-clonal SNVs from the `mutation_table` or when I added a `subclone_table` file with subclonal information. Hope this helps!

Cheers,

Tom.
